package BudgetApp.EnumClasses;
// https://familybudgetexpert.com/budget-categories/#Income
public enum ExpenseCategory {
    HOUSING, HOMESERVICES, UTILITIES, HOUSEHOLDITEMS,
    FOOD, TRANSPORTATION, MEDICAL, INSURANCE, KIDS, PETS,
    SUBSCRIPTIONS, CLOTHING, PERSONALCARE, PERSONALDEVELOPMENT,
    FINANCIALFEES, RECREATION, TRAVEL, TECHNOLOGY, GIFTS, CHARITY,
    SAVINGS, DEBTPAYMENT, OTHER;
}
